### ISSUE TITLE
Feature request: Improve documentation & examples

### ISSUE THREAD

**Issue by ckaran** [RustyYato/generic-field-projection#20]
I've been keeping an eye on this project since you started it, but my rust-fu is not good enough to be able to read the macros and know what I need to do.  Could you improve the documentation, and provide examples of how to use this project?  At some point I'd like to start writing an intrusive collections crate, and this will be the core of that work.

**Comment by KrishnaSannasi** [comment]
Ok, that sounds like a good idea

**Comment by KrishnaSannasi** [comment]
Do you have anything in particular that was unclear?

**Comment by ckaran** [comment]
Basically, I want to know what is being provided when I use this crate explicitly.  I can read the RFC, and I can read the source to see what new methods I'll have access to when I use the crate on my own structs, but having a complete set of documentation explaining what is added, why, and how to use it is better.  In short, fully flesh out **all** the documentation in the crate.

The reason I'm thinking about this is that it looks like the RFC isn't going to be a part of rust's core library anytime soon, so its better to have this crate become a complete, canonical implementation of the RFC.  As people come to use it, it will become more and more evident that it should be a part of the core library.  For this to happen, the README needs to be completed, the documentation needs to be completed and accessible from docs.rs, etc., etc., etc.  In short, everything in the [Rust API guidelines](https://rust-lang.github.io/api-guidelines/) needs to be fully implemented.

**Comment by KrishnaSannasi** [comment]
Sorry, it's been a while since I've made an update. It's been really busy for me for the last few months, so I haven't had time to look at this. I don't have any timelines for when I can get to this. If you are willing to, you can send some PRs to improve the docs and I should be able to review those in a timely fashion.

**Comment by ckaran** [comment]
> It's been really busy for me for the last few months

I fully understand!  I'm trying to finish my PhD, so I have the same problem... no time!  That said, if I'm able to get together some time, I'll try.  No promises though!
