### ISSUE TITLE
Thank you for the invite!

### ISSUE THREAD

**Issue by ckaran** [RustyYato/generic-field-projection#34]
Thank you for the invite!  If it's OK with you, I'd like to create a GitHub project board to track some of what I'm planning on doing.  That way, we both know where we're going.

**Comment by RustyYato** [comment]
Yeah, that sounds good

**Comment by RustyYato** [comment]
Moving forward, would you prefer communicating on users/internals, discord, or some other platform? Github is pretty lackluster in this department.
