### ISSUE TITLE
Remove support for unsized types

### ISSUE THREAD

**Issue by RustyYato** [RustyYato/generic-field-projection#39]
#35's fix to `Field::name` introduces a new problem, it's now not possible to project a field from a `&mut Parent` to a `&mut Field` when the `Parent` (and by extension, the `Field`) is unsized. Do we care about this use-case? Unsized types are their own can of worms, and it may be fine to ignore them for the most part in the initial implementation.

**Comment by ckaran** [comment]
I'd say ignore the unsized types for right now.  We need to get something working, and some examples to try out so we can see what other stuff needs doing.

**Comment by RustyYato** [comment]
That sounds good, I'll formally remove support for unsized types after #36 (which is a large and invasive refactor). That should simplify things a bit.
